### ISSUE TITLE
Proxies are not resolved by StringIO

### ISSUE THREAD

**Issue by WardLT** [proxystore/proxystore#109]
I found a use of a Proxy where it doesn't magically resolve: StringIO!

Let me know if you need a minimal example.
```
2022-09-12 15:14:09,186 - thinker - ERROR - store_simulation failed: initial_value must be str or None, not Proxy.
Traceback: Traceback (most recent call last):
  File "/home/lward/miniconda3/envs/fastforce/lib/python3.10/site-packages/colmena/thinker/__init__.py", line 230, in _launch_agent
    func(thinker)
  File "/home/lward/miniconda3/envs/fastforce/lib/python3.10/site-packages/colmena/thinker/__init__.py", line 47, in _result_event_agent
    process_func(thinker, result)
  File "/home/lward/Work/ExaLearn/fast-finedtuned-forcefields/colmena/initial/run.py", line 544, in store_simulation
    atoms: ase.Atoms = read_from_string(result.value, 'json')
  File "/home/lward/Work/ExaLearn/fast-finedtuned-forcefields/fff/simulation/utils.py", line 35, in read_from_string
    out = StringIO(atoms_msg)
TypeError: initial_value must be str or None, not Proxy
```

**Comment by gpauloski** [comment]
It looks like the `StringIO` implementation is in pure C so the type error is probably raised in the Python binding to the C code. This is also why there is no stacktrace from the `io` library. 

I'm not sure if there's a solution to this as the proxy model only works because of duck typing and we lose that when we go from Python to C.

**Comment by gpauloski** [comment]
I tried some alternative proxy implementations to no avail. I think C-bindings is just a hard limitation of the proxy model.

I'll leave this issue open until I add a note in the docs about this limitation with some workarounds.
```Python
import io
from proxystore.proxy import Proxy
from proxystore.proxy import extract

s = 'mystring'
p = Proxy(lambda: s)

try:
    io.StringIO(p)  # fails
except TypeError:
    pass

# Works if p is a proxy or a string (string -> string cast is no-op)
io.StringIO(str(p))

# More general solution for arbitrary c-bindings
io.StringIO(extract(p) if isinstance(p, Proxy) else p)
```

**Comment by gpauloski** [comment]
The `Proxy` docstring now has a warning for use with Python bindings to other languages.

https://proxystore.readthedocs.io/en/latest/_autosummary/proxystore.proxy.html#proxystore.proxy.proxystore.proxy.Proxy
